### ISSUE TITLE
Username Validation

### ISSUE THREAD

**Issue by ghost** [Good-Enough-Incorporated/TaskTok#1]
In auth.py, create user input validation for when the user creates a username for their TaskTok account.

Ensure that the input from the user is:
- Valid characters (Mixture of numbers and letters are valid. Only numbers are not valid)
- Within range (4-20 characters)
- Is a string still after validation

**Comment by divyakelaskar** [comment]
Can I work on this one?

**Comment by jaciares** [comment]
Ummm... who are you?

**Comment by ghost** [comment]
Validation based on original issue # 1 requirements, completed. Refer to issue #15 for further validation.

**Comment by beatles1235** [comment]
issue implemented by @jfergesonumgc
