### ISSUE TITLE
Register allows for non email addresses

### ISSUE THREAD

**Issue by beatles1235** [Good-Enough-Incorporated/TaskTok#13]
When a new user is registering, the flask_wtf is not validating if the email address is a valid email

example:

email: hello
username: user123
password: sdkdfjlkjds

user is able to register despite the email address clearly not being the valid format of hello@example.com

if the email is not the correct format, a flash message should appear saying 'bad_email' is not a valid email address.

**Comment by jfergesonumgc** [comment]
This should be good now.

**Comment by beatles1235** [comment]
email validation implemented by @jfergesonumgc
