### ISSUE TITLE
Username should be case insensitive

### ISSUE THREAD

**Issue by beatles1235** [Good-Enough-Incorporated/TaskTok#15]
When creating the username, we should save the username as lowecase, and compare all user input as lowercase to avoid having case sensitive usernames.

test: Admin

invalid user/password since Admin does not exist (admin does though)

**Comment by jfergesonumgc** [comment]
I can add this while doing validation.

**Comment by beatles1235** [comment]
issue resolved in dev branch by bbe1dc1fc251844fec506a294c8074b8ebb25696
