### ISSUE TITLE
Email Verification Functionality 

### ISSUE THREAD

**Issue by ghost** [Good-Enough-Incorporated/TaskTok#7]
Need email verification system for user registration and password resets.

Here is what I have in mind.

1. User registers their account
2. Backend code will store and generate the user's verification token.
3. Send an email to user's email address with a link to a verification endpoint.
4. If the user's token is valid and matches, update user's `is_verified` status or whatever boolean you use.

Few things to keep in mind:
- Works with WTForms or our custom validation.
- USE SendGrid https://docs.sendgrid.com/for-developers/sending-email/quickstart-python

Backend:
- Setup SendGrid
- Modify the DB to include a column for email verification (for ex. `is_verfied` boolean)
- Have a function that generates a secure and unique token for each user. You can use a library of your choice for this but UUID python library might be the best option IMO https://docs.python.org/3/library/uuid.html

Front-end:
- Just make a simple placeholder to reflect the verification status. For example, "Verification email has been sent!"
- Don't worry about making everything pretty.

Testing:
- I am not sure atm how email testing will work for multiple people. Here are some docs about email testing using SendGrid
https://docs.sendgrid.com/ui/sending-email/email-testing#maincontent
- Worst case, we all make accounts to test this functionality.

**Comment by beatles1235** [comment]
resolved in dev by bbe1dc1fc251844fec506a294c8074b8ebb25696
